costmap:
  costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 20
      height: 20
      resolution: 0.15
      plugins: ["inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.7

planner_server:
  ros__parameters:
    expected_planner_frequency: 2.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.5
      max_iterations: 1000000
      minimum_turning_radius: 0.5
      reverse_penalty: 2.0
      cost_travel_multiplier: 2.0

    global_costmap:
      ros__parameters:
        update_frequency: 1.0
        publish_frequency: 1.0
        global_frame: odom
        robot_base_frame: base_link
        use_sim_time: True
        rolling_window: true # Key for Odom-only navigation
        track_unknown_space: true
        width: 40.0
        height: 40.0
        resolution: 0.15
        plugins: ["obstacle_layer", "inflation_layer"]
        
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: True
          observation_sources: slope_map
          slope_map:
            topic: /height_traversability_costmap
            data_type: OccupancyGrid # Use your script as an obstacle source
            clearing: false
            marking: true

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 0.7